name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    env:
      LOCAL_VAR: "Local value"

    steps:
      - name: Print hello world
        run: echo "hello world"

      - name: Use secret password
        run: echo "The password is ${{ secrets.BARWAR_BANY }}"

  