name: Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  hellp-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello world
        run: echo "hello world"

      - name: Use secret password (barwar_bany)
        run: echo "The password is ${{ secrets.barwar2004 }}"
